### ISSUE TITLE
S3 Bucket

### ISSUE THREAD

**Issue by joeghal** [aws/amazon-braket-strawberryfields-plugin-python#4]
Hello,

Is it possible to bypass the PutPublicAccessBlock call in S3 buckets? There is a policy at my organization that forbids any change associated with them and I am therefore not able to launch any Xanadu Borealis instance with the plugin because of that issue.
I get an AccessDenied error.

Your help would be greatly appreciated!

**Comment by virajvchaudhari** [comment]
Hi @joeghal,

By providing your default bucket name when creating the task, you can get around the policy error. You are now encountering this problem because the default bucket we setup needs this policy.

**Comment by virajvchaudhari** [comment]
Hi @joeghal,
 
Based on the earlier suggestion made in response to your query, I will close this issue. If your still facing the issue, please feel free to re-open this issue.
